# Generated by Django 5.2.7 on 2026-03-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_purchase',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
